ADDONS_PATH=.
KC_URL=https://login-test.symple.cloud/auth/realms/sorgenia-test-02/protocol/openid-connect/token
KC_USER=integration.b2w@symple.com
KC_PASSWORD=op://Dev/keycloak-agrippa/password
KC_ID=client-sorgenia-test-02
KC_SECRET=op://Dev/keycloak-agrippa/client_secret
RIP_URL=https://odoo.sorgenia-test-02.symple.cloud/rip/v3/api
TRIDENT_URL=https://trident-agora.odoo.com
TRIDENT_UID=279
TRIDENT_TOKEN=op://Dev/trident/credential
DEVOPS_TOKEN=op://Dev/azure-devops/credential
DEVOPS_ORG=symphonie-partners
DEVOPS_PROJECT=B2IT - Sorgenia - Progetto TG e ML
DEVOPS_REPO=sorgenia_addons
TRIDENT_DB=trident-agora
AUTOPR_TARGET_BRANCH=15.0-dev
IMPORTEXPORT_URL=https://sorgenia-test-02.symple.cloud/api/importexport/v1/
PB_URL=https://sorgenia-test-02.symple.cloud/api/processbuilder/v1
